version: "2"

services:
  rdb:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD

  adminer:
    image: adminer
    ports:
      - 9088:8080
    depends_on:
      - rdb